name: Execute tests
on:
  push:
    tags:
      - '*'
    branches: ['dev']
jobs:
  Execute-tests:
    runs-on: ubuntu-20.04
  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Run tests
        run: ./mvnw install